-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: a10dec1998af6c70e26b8e6f419f93018b264253
    hooks:
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: git://github.com/asottile/reorder_python_imports
    sha: f5c67b716c04babb6e8e80bb52e329ee7654b1b8
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/Yelp/detect-secrets
    sha: 0.9.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|\.pre-commit-config\.yaml
        language_version: python2.7
