language: python
matrix:
  include:
    - env: TOXENV=py27
      python: '2.7'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=pre-commit

install: sudo pip install tox-travis

script: tox
deploy:
  provider: pypi
  user: yelplabs
  skip_existing: true
  password:
    secure: WMygawcYeJGbe4cJlQECKKEZJLYsirgutlihp8Yn4iAKRjpDFmOTwB0B8NjaYsB9pBvz7MLz913ukIhzsHhZLMYE6GRpwjiGfaSXupC4zDVkdi14KPJIo7dff/1p0rGGtZmYa/iohC/HDgbF4iXcBcwdzrvDBDqwPFaM/5J4LxF+KunXCVopsmQTkBEsMNz/K55By3xCO3qxupixTDYy+VOVv3F6Bs8hChqKmql9vvi2ZZPVq9y7io13T7JREKKv8ZOyIq+AGXtrZvnzVuNPfW6PE3eBUv2BUy0xEuwsqjX4goQ0bzRiVKS4XdIl8HmZD/aj2mkaXSw6HLST4+/+im2uNVIPHTEfyqDgUwtZInQF9zML3wGANGIfS+z1ZKfirSO0DiTKpFMkbiM5K0D+VRKFChblCOqQ5WiU9jhcLrHDHED7aLT7pIAlEcizeTpTwF9ZR5Eg48wB59A3q5b6aTsw1t9Q2kIyEnXHgf3JUGtRu0BO2ATGL324Dkzoa8DN2CeZ0F3fWCaI7gqFssrytDPwG+ct17yJkLQXnRTemFm/fCw9YC+onSufa+pV2qlRZRFywifgwIaAwL7hXC4w2qF4d5RzEOtCZjlmOBCLZ6/r/dwhnS+bBdHSuxxcfV1WB5RZLemqNJfbRdQheM0Ld6tzqZZRi5SB7gohnLEJWlc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Yelp/osxcollector_output_filters
    branch: master
